Open/Open/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Main Home Visitor page
    url(r'^', include('home.urls')),

    # Profiles page
    url(r'^userProfiles/', include('userProfiles.urls', namespace='userProfiles')),

    # Admin backend
    url(r'^admin/', admin.site.urls),

    # Requests page
    url(r'^requests/', include('requests.urls', app_name='requests', namespace='requests')),

    # User auth urls
    # url(r'^register/$', views.UserFormRegisterView.as_view(), name='register'),
    url(r'^accounts/', include('accounts.urls', app_name='accounts', namespace='accounts')),

    #Msesages
    url(r'^Messages/', include('Messages.urls', app_name='Messages', namespace='Messages')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Open/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts import views as core_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'index'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),

]

Open/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

Open/requests/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.index, name='matchedUsers'),
    #url(r'^sendRequest$', views.sendRequest, name='sendRequest'),
    url(r'^sendRequest/(?P<operation>.+)/(?P<pk>\d+)/$', views.sendRequest, name='sendRequest')
]

Open/userProfiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^post/new/$', views.post_new, name='post_new'),
    #url(r'^choseninterest/$', views.choseninterest, name='choseninterest'),
    url(r'^edit_userinfo/$', views.edit_userinfo, name='edit_userinfo'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^other_users/$', views.other_users, name='other_users'),
    url(r'^other_users/(?P<pk>\d+)/$', views.other_users, name='other_users_with_pk'),
    url(r'^user_questionnaire/$', views.user_questionnaire, name='user_questionnaire'),

]

Open/templates/footer.html
 <footer>
     <b >&mdash; Copyright <span style="font-size: 21px"> &copy; </span>2017 Somebody Really Really Interesting</b>
</footer>

Open/templates/interestsTable.html
<div class="container-fluid bg-1">

   <div class="row">

       <div class="col-sm-10">

  <h3>My Interests</h3>
           <div class="page-header">
    <a href="{% url 'userProfiles:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span>Edit Interests</a>


</div>
  <table class="table">
    {% for selected in user.userprofile.interest_type.all %}
    <tbody>
      <tr>
          <td><strong>{{ selected }}</strong>{% endfor %}</td>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

Open/templates/matchedUsers.html
<!DOCTYPE html>
<html lang="en">
    <div>
        <h3>Suggested Mathches</h2>
        <!-- once we have a matching algorithm the loop with be for users in matched users-->
        {% for user in users %}
            {% if not user in friends %}
            <a href="{% url 'requests:matchedUsers' pk=user.pk %}">
                <h4>{{ user.username }}</h3>
            </a>
                <a href="{% url 'requests:sendRequest' operation='add' pk=user.pk %}">
                    <button type="button" class="btn btn-success">Send Request</button>
                </a>
            {% endif %}
        {% endfor %}
        <h3>Requests</h3>
        <!-- (people who requested a date with you will show) -->
        {% for friend in friends %}
            <a href="{% url 'requests:matchedUsers' pk=friend.pk %}">
                <h4>{{ friend.username }}</h3>
            </a>
            <a href="{% url 'requests:sendRequest' operation='remove' pk=friend.pk %}">
                <button type="button" class="btn btn-default">Cancel Request</button>
            </a>
        {% endfor %}
    </div>
</html>

Open/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar" >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{%url 'index' %}" font size="20">OPEN</font></a>
            {% else %}
                <a class="navbar-brand" href="{%url 'index' %}" font size="20">Welcome Visitor!</font></a>
            {% endif %}
        </div>

        <!-- Menu Items -->
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="topNavBar">
                   <ul class="nav navbar-nav navbar-right">
                     <li class="">
                        <a href="{% url 'userProfiles:index' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> My Profile
                        </a>
                    </li>
                       <li class="">
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>

                </ul>
            </div>
     {% else %}
        <div class="collapse navbar-collapse" id="topNavBar">
               <ul class="nav navbar-nav navbar-right">
                <li class="">
                 <a href="{% url 'accounts:signup' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; User Register
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'accounts:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
            </ul>
        </div>
     {% endif %}

    </div>
</nav>

Open/templates/profilePreview.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{%  block title %}Users{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
       <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>
    <body>
        <title>Browse</title>
        {% block body %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <div class="text-center" >
                        <img src="../../static/images/generic.png" class="img-circle" alt="Generic pic" width="300" height="300" >
                    </div>
                    <div class="text-center">
                        <div class="rating-block">
                            <button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 " style="background-color:WhiteSmoke ;">
                    <div class="text-left">
                        <h1>Username:{{ user }}</h1>
                        <h1>Name:{{ user.first_name }}</h1>
                        <h1>Last:{{ user.last_name }}</h1>
                        <h4 ><strong>Location: </strong> Placeholder</h4>
                        <h4><strong>Sex: </strong>Placeholder </h4>
                        <h4><strong>Age: </strong>Placeholder</h4>
                        <h4><strong>Email:</strong>{{user.email}}</h4>            
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </body>
</html>

Open/templates/profileSideNav.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
</head>
<nav class="navbar navbar-inverse sidebar" role="navigation">

    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
                <img src="../../static/images/open175.png" class="img-rounded" alt="open">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"></a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="{%url 'index' %}">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
			<br>
              <li ><a href="{% url 'userProfiles:index' %}">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
			<br>
              <li ><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
            <br>
				<li><a href="{% url 'requests:index' %}">Requests<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-inbox"></span></a></li>
			<br>
              <li ><a href="{% url 'userProfiles:other_users' %}">Browse<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
			</ul>
		</div>
	</div>
</nav>
<div class="main">
<!-- Content Here -->
</div>
</html>

Open/templates/userInfo.html
<div class="container-fluid" style="background-color:WhiteSmoke ;" xmlns="http://www.w3.org/1999/html">
  <div class="row ">
    <div class="col-sm-6">
                    <div class="text-center" >
                        <img src="../../static/images/generic.png" class="img-circle" alt="Generic pic" width="300" height="300" >
                    </div>
                <div class="text-center">
				<div class="rating-block">
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
				</div>
            </div>
    </div>
    <div class="col-sm-6 " style="background-color:WhiteSmoke ;">
        <div class="text-left">
            <h2>Username:<strong>{{user}}</strong></h2>
            <h2>Name:{{ user.first_name }}</h2>
            <h2>Last:{{ user.last_name }}</h2>
            <h4 >Location: <strong> {{ user.userprofile.user_location }}</strong></h4>
            <h4>Sex: <strong>{{ user.userprofile.user_gender }}</strong> </h4>
            <h4>Birthday: <strong>{{ user.userprofile.user_birthday }}</strong></h4>
            <h4>Email:<strong>{{user.email}}</strong></h4>

            <a href="{% url 'userProfiles:edit_userinfo' %}" class="btn btn-info" role="button">Edit</a>
        </div>
    </div>
  </div>
</div>


<!--
<div class="container-fluid">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#popUpWindow"> Edit interests</button>

    <div class="modal fade" id="popUpWindow">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <img src="../static/images/Open225x256.png" class="img-rounded" alt="open" >
                    <h3 class="modal-title">What Are Your Interests?</h3>
                </div>

                <div class="modal-body">

                    <p>Hello</p>
                     {% for post in posts %}
                        <h4>{{ post }}</h4> <br>
                     {% endfor %}

                </div>

                <div class="modal-footer">
                <button type="button" class="btn">Submit</button>

                </div>

            </div>

        </div>


    </div>

</div>
-->

Open/templates/visitor_navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar" >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="#" {#<!--{%url 'open:home %}-->#}><font size="20">OPEN</font></a>
            {% else %}
                <a class="navbar-brand" href="#" {#<!--{%url 'open:home %}-->#}><font size="20">Welcome Visitor!</font></a>
            {% endif %}
        </div>

        <!-- Menu Items -->
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="topNavBar">
                   <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
     {% else %}
        <div class="collapse navbar-collapse" id="topNavBar">
               <ul class="nav navbar-nav navbar-right">
                <li class="">
                 <a href="#" {# <!--{% url 'open:register' %}"-->#}>
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; User Register
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'accounts:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
            </ul>
        </div>
     {% endif %}

    </div>
</nav>