Open/Open/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Main Home Visitor page
    url(r'^', include('home.urls')),

    # Profiles page
    url(r'^userProfiles/', include('userProfiles.urls', namespace='userProfiles')),

    # Admin backend
    url(r'^admin/', admin.site.urls),

    # Requests page
    url(r'^requests/', include('requests.urls', app_name='requests', namespace='requests')),

    # User auth urls
    # url(r'^register/$', views.UserFormRegisterView.as_view(), name='register'),
    url(r'^accounts/', include('accounts.urls', app_name='accounts', namespace='accounts')),

    #Msesages
    url(r'^Messages/', include('Messages.urls', app_name='Messages', namespace='Messages')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Open/userProfiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^post/new/$', views.post_new, name='post_new'),
    #url(r'^choseninterest/$', views.choseninterest, name='choseninterest'),
    url(r'^edit_userinfo/$', views.edit_userinfo, name='edit_userinfo'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^other_users/$', views.other_users, name='other_users'),
    url(r'^other_users/(?P<pk>\d+)/$', views.other_users, name='other_users_with_pk'),
    url(r'^user_questionnaire/$', views.user_questionnaire, name='user_questionnaire'),

]

Open/userProfiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    interest_type = models.ManyToManyField('Interests', blank=True)
    user_location = models.CharField(max_length=250,default='Any', editable=True)
    FEMALE = 'FM'
    MALE = 'ML'
    USER_Gender_CHOICES = (
        (FEMALE, 'Female'),
        (MALE, 'Male'),
    )
    user_gender = models.CharField(
        max_length=2,
        choices=USER_Gender_CHOICES,
        default=MALE,
    )
    user_birthday = models.DateField(blank=True, null=True)
    user_gender_pref = models.ManyToManyField('GenderPreference', blank=True)
    partner_location_preference = models.CharField(max_length=250,default='Any', editable=True)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class Interests(models.Model):
    userInterests = models.CharField(max_length=250)
    #user_details = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    # def_str returns the names of items in database

    def __str__(self):
        return self.userInterests

class GenderPreference(models.Model):
    gender_pref_choice = models.CharField(max_length=250)

    def __str__(self):
        return self.gender_pref_choice

Open/userProfiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from .models import Interests, UserProfile, GenderPreference


class UserForm(forms.ModelForm):
    user_gender_pref = forms.ModelMultipleChoiceField(queryset=GenderPreference.objects.all(), widget=forms.CheckboxSelectMultiple(),label='Gender Preference')
    class Meta:
        model = UserProfile
        fields = ('user_location', 'user_birthday', 'user_gender','user_gender_pref', 'partner_location_preference',)
        labels = {
            'user_location': ('Location'),
            'user_birthday': ('Birthday'),
            'user_gender': ('Gender'),
            'user_gender_pref':('Gender Preference'),
            'partner_location_preference':('Look For Match In'),
        }

class InterestsForm(forms.ModelForm):
    interest_type = forms.ModelMultipleChoiceField(queryset=Interests.objects.all(), widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = UserProfile
        fields = ('interest_type',)


class editUserInfoForm(UserChangeForm):

    class Meta:
        model = User
        fields= (
            'email',
            'first_name',
            'last_name',
            'password',

        )

Open/userProfiles/views.py
from django.shortcuts import render, redirect
from .forms import editUserInfoForm
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
#from .models import Interests
from .forms import InterestsForm, UserForm
# Create your views here.
# @login required doesnt allow user to access particular view if not authenticated


@login_required
def index(request):
   # posts = Interests.objects.all()
    args = {'user': request.user}
    return render(request, 'userProfiles/UserProfiles.html',args)# , {'posts': posts}

@login_required
def other_users(request, pk=None):
   # form = InterestsForm()
    users = User.objects.exclude(id=request.user.id)
    if pk:
       user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user, 'users': users}
    return render(request, 'userProfiles/otherUsers.html', args)


def user_questionnaire(request):
    try: profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = UserForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('/userProfiles')
    else:
        form = UserForm(instance=profile)
        args = {'form': form}
        return render(request, 'userProfiles/questionnaire.html', args)


# This view is for Interests form
@login_required
def post_new(request):
    try: profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = InterestsForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('/userProfiles')
    else:
        form = InterestsForm(instance=profile)
        args = {'form': form}
        return render(request, 'userProfiles/interestsModal.html', args)


@login_required
def edit_userinfo(request):
    if request.method == 'POST':
        form = editUserInfoForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/userProfiles')
    else:
        form = editUserInfoForm(instance=request.user)
        args = {'form':form}
        return render(request, 'userProfiles/edit_userinfo.html',args)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('/userProfiles')
        else:
            return redirect('/userProfiles/change-password')
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request,'userProfiles/change_password.html', args)

Open/userProfiles/templates/otherUsersInfo.html
<div class="container-fluid" style="background-color:WhiteSmoke ;" xmlns="http://www.w3.org/1999/html">
  <div class="row ">
    <div class="col-sm-6">
                    <div class="text-center" >
                        <img src="../../../static/images/generic.png" class="img-circle" alt="Generic pic" width="300" height="300" >
                    </div>
                <div class="text-center">
				<div class="rating-block">
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					</button>
				</div>
            </div>
    </div>
    <div class="col-sm-6 " style="background-color:WhiteSmoke ;">
        <div class="text-left">
            <h2>Username:<strong>{{user}}</strong></h2>
            <h2>Name:{{ user.first_name }}</h2>
            <h2>Last:{{ user.last_name }}</h2>
            <h4 >Location: <strong> {{ user.userprofile.user_location }}</strong></h4>
            <h4>Sex: <strong>{{ user.userprofile.user_gender }}</strong> </h4>
            <h4>Birthday: <strong>{{ user.userprofile.user_birthday }}</strong></h4>
            <h4>Email:<strong>{{user.email}}</strong></h4>

            <a href="{% url 'userProfiles:edit_userinfo' %}" class="btn btn-info" role="button">Edit</a>
        </div>
    </div>
  </div>
</div>


<!--
<div class="container-fluid">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#popUpWindow"> Edit interests</button>

    <div class="modal fade" id="popUpWindow">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <img src="../static/images/Open225x256.png" class="img-rounded" alt="open" >
                    <h3 class="modal-title">What Are Your Interests?</h3>
                </div>

                <div class="modal-body">

                    <p>Hello</p>
                     {% for post in posts %}
                        <h4>{{ post }}</h4> <br>
                     {% endfor %}

                </div>

                <div class="modal-footer">
                <button type="button" class="btn">Submit</button>

                </div>

            </div>

        </div>


    </div>

</div>
-->

Open/userProfiles/templates/profileSideNav2.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
</head>
<nav class="navbar navbar-inverse sidebar" role="navigation">

    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
                <img src="../../../static/images/open175.png" class="img-rounded" alt="open">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#"></a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="{%url 'index' %}">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
			<br>
              <li ><a href="{% url 'userProfiles:index' %}">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
			<br>
              <li ><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
            <br>
				<li><a href="{% url 'requests:index' %}">Requests<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-inbox"></span></a></li>
			<br>
              <li ><a href="{% url 'userProfiles:other_users' %}">Browse<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-search"></span></a></li>
			<br>
              <li ><a href="{% url 'userProfiles:user_questionnaire' %}">Settings<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a></li>
			<br>
				<li ><a href="#">Matches<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-heart"></span></a></li>
			</ul>
		</div>
	</div>
</nav>
<div class="main">
<!-- Content Here -->
</div>
</html>