Open/Open/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Main Home Visitor page
    url(r'^', include('home.urls')),

    # Profiles page
    url(r'^userProfiles/', include('userProfiles.urls', namespace='userProfiles')),

    # Admin backend
    url(r'^admin/', admin.site.urls),

    # Requests page
    url(r'^requests/', include('requests.urls', app_name='requests', namespace='requests')),

    # User auth urls
    # url(r'^register/$', views.UserFormRegisterView.as_view(), name='register'),
    url(r'^accounts/', include('accounts.urls', app_name='accounts', namespace='accounts')),

    #Msesages
    url(r'^Messages/', include('Messages.urls', app_name='Messages', namespace='Messages')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Open/userProfiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^post/new/$', views.post_new, name='post_new'),
    #url(r'^choseninterest/$', views.choseninterest, name='choseninterest'),
    url(r'^edit_userinfo/$', views.edit_userinfo, name='edit_userinfo'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^other_users/$', views.other_users, name='other_users'),
    url(r'^other_users/(?P<pk>\d+)/$', views.other_users, name='other_users_with_pk'),
    url(r'^user_questionnaire/$', views.user_questionnaire, name='user_questionnaire'),

]

Open/userProfiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    interest_type = models.ManyToManyField('Interests', blank=True)
    user_location = models.CharField(max_length=250,default='Any', editable=True)
    FEMALE = 'FM'
    MALE = 'ML'
    USER_Gender_CHOICES = (
        (FEMALE, 'Female'),
        (MALE, 'Male'),
    )
    user_gender = models.CharField(
        max_length=2,
        choices=USER_Gender_CHOICES,
        default=MALE,
    )
    user_birthday = models.DateField(blank=True, null=True)
    user_gender_pref = models.ManyToManyField('GenderPreference', blank=True)
    partner_location_preference = models.CharField(max_length=250,default='Any', editable=True)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class Interests(models.Model):
    userInterests = models.CharField(max_length=250)
    #user_details = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    # def_str returns the names of items in database

    def __str__(self):
        return self.userInterests

class GenderPreference(models.Model):
    gender_pref_choice = models.CharField(max_length=250)

    def __str__(self):
        return self.gender_pref_choice

Open/userProfiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from .models import Interests, UserProfile, GenderPreference


class UserForm(forms.ModelForm):
    user_gender_pref = forms.ModelMultipleChoiceField(queryset=GenderPreference.objects.all(), widget=forms.CheckboxSelectMultiple(),label='Gender Preference')
    class Meta:
        model = UserProfile
        fields = ('user_location', 'user_birthday', 'user_gender','user_gender_pref', 'partner_location_preference',)
        labels = {
            'user_location': ('Location'),
            'user_birthday': ('Birthday'),
            'user_gender': ('Gender'),
            'user_gender_pref':('Gender Preference'),
            'partner_location_preference':('Look For Match In'),
        }

class InterestsForm(forms.ModelForm):
    interest_type = forms.ModelMultipleChoiceField(queryset=Interests.objects.all(), widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = UserProfile
        fields = ('interest_type',)


class editUserInfoForm(UserChangeForm):

    class Meta:
        model = User
        fields= (
            'email',
            'first_name',
            'last_name',
            'password',

        )

Open/userProfiles/views.py
from django.shortcuts import render, redirect
from .forms import editUserInfoForm
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
#from .models import Interests
from .forms import InterestsForm, UserForm
# Create your views here.
# @login required doesnt allow user to access particular view if not authenticated


@login_required
def index(request):
   # posts = Interests.objects.all()
    args = {'user': request.user}
    return render(request, 'userProfiles/UserProfiles.html',args)# , {'posts': posts}

@login_required
def other_users(request, pk=None):
   # form = InterestsForm()
    users = User.objects.exclude(id=request.user.id)
    if pk:
       user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user, 'users': users}
    return render(request, 'userProfiles/otherUsers.html', args)


def user_questionnaire(request):
    try: profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = UserForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('/userProfiles')
    else:
        form = UserForm(instance=profile)
        args = {'form': form}
        return render(request, 'userProfiles/questionnaire.html', args)


# This view is for Interests form
@login_required
def post_new(request):
    try: profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = InterestsForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('/userProfiles')
    else:
        form = InterestsForm(instance=profile)
        args = {'form': form}
        return render(request, 'userProfiles/interestsModal.html', args)


@login_required
def edit_userinfo(request):
    if request.method == 'POST':
        form = editUserInfoForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/userProfiles')
    else:
        form = editUserInfoForm(instance=request.user)
        args = {'form':form}
        return render(request, 'userProfiles/edit_userinfo.html',args)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('/userProfiles')
        else:
            return redirect('/userProfiles/change-password')
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request,'userProfiles/change_password.html', args)

Open/userProfiles/templates/userProfiles/change_password.html
        <meta charset="UTF-8">
        <title>{%  block title %}Change Password{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


{% include 'navbar.html' %}
<div class="row">

      <div class="col-xs-9 col-md-9 text-center">
        <!-- Teal page content  -->
              <form method="post">
              {% csrf_token %}
              {{ form.as_p}}
              <button type="submit">Submit</button>
              </form>

      </div>

      <div class="col-xs-3 col-md-3">
          <!-- Grey navigation panel -->
          {% include 'authenticated_navbar.html' %}

      </div>

    </div>
{% include 'footer.html' %}

Open/userProfiles/templates/userProfiles/edit_userinfo.html
 <meta charset="UTF-8">
        <title>{%  block title %}Change Password{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{% include 'navbar.html' %}
<div class="row">

      <div class="col-md-10 text-center">
        <!-- Teal page content  -->
              <form method="post">
              {% csrf_token %}
              {{ form.as_p}}
              <button type="submit">Submit</button>
              </form>

        <a href="{% url 'userProfiles:change_password' %}" class="btn btn-info" role="button">Change Password</a>
      </div>

      <div class=" col-md-2">
          <!-- Grey navigation panel -->
          {% include 'profileSideNav.html' %}

      </div>

    </div>
{% include 'footer.html' %}

Open/userProfiles/templates/userProfiles/interestsModal.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
        <meta charset="UTF-8">
        <title>{%  block title %}Interests{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
       <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    </head>
<body>
{%include 'navbar.html'%}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 text-center">
{% block content %}
    <h1>What are your Interests?</h1>
    <form method="POST" >
        {% csrf_token %}
        {{ form }}
        <br><button type="submit" class="save btn btn-default">Submit</button>
    </form>


        </div>

        <div class="col-md-2">
{% include 'profileSideNav.html' %}

        </div>

    </div>

</div>

</body>
{% endblock %}
</html>

Open/userProfiles/templates/userProfiles/otherUsers.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <title>{%  block title %}Browse Users{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
       <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    </head>

<title>Browse</title>
 {% block body %}

{%include 'navbar.html'%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
             <h3>Browse Users</h3>
    {% for user in users%}
        <a href="{% url 'userProfiles:other_users_with_pk' pk=user.pk %}">
        <h3>{{user.username}}</h3>
    </a>
    {% endfor %}


        </div>
        <div class="col-md-8">
        {% include 'otherUsersInfo.html' %}
        </div>
        <div class="col-md-2">
{% include 'profileSideNav2.html' %}

        </div>
    </div>
</div>
{% endblock %}
</html>

Open/userProfiles/templates/userProfiles/questionnaire.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}Questionnaire{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
{% include 'navbar.html' %}
<div class="row">

      <div class="col-md-10 text-center">
        <h2> Tell us a bit about you</h2>
              <form method="post">
              {% csrf_token %}
              {{ form.as_p}}
              <button type="submit">Submit</button>
              </form>
      </div>

      <div class=" col-md-2">
          <!-- Grey navigation panel -->
          {% include 'profileSideNav.html' %}

      </div>

    </div>
{% include 'footer.html' %}

</body>
</html>

Open/userProfiles/templates/userProfiles/userProfiles.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <title>{%  block title %}Home{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
       <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/userProfiles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    </head>
<header>

</header>
<body>

{%include 'navbar.html'%}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
{% include 'userInfo.html' %}
 {% include 'interestsTable.html' %}
        </div>

        <div class="col-md-2">
{% include 'profileSideNav.html' %}

        </div>

    </div>

</div>



</body>

</html>